[tool.poetry]
name = "cmp"
version = "1.0.1"
description = "Contextual matrix profile for anomaly detection in building electrical loads"
authors = ["RobertoChiosa <roberto.chiosa@polito.it>"]
readme = "README.md"
packages = [
    { include = "src/cmp" },
    { include = "src/distancematrix" },
]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.2"
plotly = "^5.22.0"
scipy = "^1.14.0"
matplotlib = "^3.9.1"
seaborn = "^0.13.2"
kneed = "^0.8.5"
jinja2 = "^3.1.4"
argparse = "^1.4.0"
logger = "^1.4"
requests = "^2.32.4"
numpy = "^2.2.1"
holidays = "^0.64"
scikit-learn = "^1.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

